services:
  ipp-nginx:
    image: ipp-nginx-80:${IMAGE_TAG}
    container_name: ipp-nginx-container
    ports:
      - "3000:80"
    networks:
      - ipp-network
    volumes:
      - ipp-nginx-logs:/var/log/nginx
    restart: unless-stopped

networks:
  ipp-network:
    driver: bridge

volumes:
  ipp-nginx-logs:
